# Generated by Django 4.2.7 on 2023-11-21 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('home_address', models.CharField(max_length=200)),
                ('contact_num', models.CharField(max_length=15)),
                ('user_bio', models.TextField(blank=True, max_length=500, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/default.png', upload_to='static/profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('preferenceId', models.CharField(default=users.models.generate_preference_key, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('preferredAnimalType', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Any', 'Any')], default='', max_length=20)),
                ('preferredBreed', models.CharField(choices=[('Puspin', 'Puspin'), ('Aspin', 'Aspin'), ('Any', 'Any')], default='Any', max_length=20)),
                ('preferredAge', models.CharField(choices=[('Puppy/Kitten', 'Puppy/Kitten'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior'), ('Any', 'Any')], default='', max_length=20)),
                ('preferredGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=20)),
                ('preferredSize', models.CharField(choices=[('Extra Small', 'Extra Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Any', 'Any')], default='', max_length=20)),
                ('preferredColor', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Orange', 'Orange'), ('Cream', 'Cream'), ('Bi-color', 'Bi-color'), ('Tricolor', 'Tricolor'), ('Any', 'Any')], default='', max_length=20)),
                ('preferredSpayedorNeutered', models.BooleanField()),
                ('preferredHealthCondition', models.CharField(choices=[('Healthy', 'Healthy'), ('With Disease/Illness', 'With Disease/Illness'), ('Chronic Condition', 'Chronic Condition'), ('Under Treatment', 'Under Treatment'), ('Recovering', 'Recovering'), ('Injured', 'Injured'), ('Behavioral Issues', 'Behavioral Issues'), ('Senior Care', 'Senior Care'), ("I don't mind", "I don't mind")], default='', max_length=30)),
                ('preferredPersonality', models.CharField(choices=[('Playful', 'Playful'), ('Cuddly', 'Cuddly'), ('Energetic', 'Energetic'), ('Laid_back', 'Laid-back'), ('Curious', 'Curious'), ('Social', 'Social'), ('Independent', 'Independent'), ('Shy/Timid', 'Shy/Timid'), ('Bold/Confident', 'Bold/Confident'), ('Intelligent', 'Intelligent'), ('Mischievous', 'Mischievous'), ('Reserved', 'Reserved'), ('Protective', 'Protective'), ('Adventurous', 'Adventurous'), ('Affectionate', 'Affectionate'), ('Patient', 'Patient'), ('Stubborn', 'Stubborn'), ('Gentle', 'Gentle'), ('Sociable', 'Sociable'), ('Talkative', 'Talkative')], default='', max_length=50)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
