# Generated by Django 4.2.7 on 2023-11-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationAmount',
            field=models.DecimalField(choices=[('300', '300'), ('200', '200'), ('3000', '3000'), ('50', '50'), ('70', '70'), ('500', '500'), ('1000', '1000'), ('100', '100'), ('2000', '2000'), ('700', '700'), ('20', '20')], decimal_places=2, max_digits=8),
        ),
    ]
