# Generated by Django 4.2.7 on 2023-11-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_donationamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationAmount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
