[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
aptPkgs = ["...", "libcairo2-dev", "pkg-config", "python3-dev"]
