# Generated by Django 4.2.2 on 2023-11-24 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicationId', models.CharField(default=pets.models.generate_application_key, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('adopterFirstName', models.CharField(max_length=50)),
                ('adopterLastName', models.CharField(max_length=50)),
                ('adopterHomeAddress', models.CharField(max_length=300)),
                ('adopterContactNum', models.CharField(max_length=15)),
                ('picture', models.ImageField(default='static/default.png', upload_to='static/application_pics')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Interviewing', 'Interviewing'), ('Accepted', 'Accepted'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected'), ('Evaluating', 'Evaluating'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petId', models.CharField(default=pets.models.generate_pet_key, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('petName', models.CharField(max_length=50, unique=True)),
                ('animalType', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Others', 'Others')], max_length=20)),
                ('breed', models.CharField(max_length=50)),
                ('petAge', models.CharField(choices=[('Puppy/Kitten', 'Puppy/Kitten'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=50)),
                ('petGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20)),
                ('petSize', models.CharField(choices=[('Extra Small', 'Extra Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20)),
                ('petColor', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Orange', 'Orange'), ('Cream', 'Cream'), ('Bi-color', 'Bi-color'), ('Tricolor', 'Tricolor')], default='', max_length=20)),
                ('petDescription', models.TextField(blank=True, max_length=500, null=True)),
                ('petPersonality', models.CharField(choices=[('Playful', 'Playful'), ('Cuddly', 'Cuddly'), ('Energetic', 'Energetic'), ('Laid_back', 'Laid-back'), ('Curious', 'Curious'), ('Social', 'Social'), ('Independent', 'Independent'), ('Shy/Timid', 'Shy/Timid'), ('Bold/Confident', 'Bold/Confident'), ('Intelligent', 'Intelligent'), ('Mischievous', 'Mischievous'), ('Reserved', 'Reserved'), ('Protective', 'Protective'), ('Adventurous', 'Adventurous'), ('Affectionate', 'Affectionate'), ('Patient', 'Patient'), ('Stubborn', 'Stubborn'), ('Gentle', 'Gentle'), ('Sociable', 'Sociable'), ('Talkative', 'Talkative')], default='', max_length=50)),
                ('dateAcquired', models.DateField(default=django.utils.timezone.now)),
                ('isTrained', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('adoptedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnoverDate', models.DateField(blank=True, null=True)),
                ('turnoverTime', models.TimeField(blank=True, default=None, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.application')),
            ],
        ),
        migrations.CreateModel(
            name='PetMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petWeight', models.IntegerField()),
                ('isVaccinated', models.BooleanField()),
                ('isNeutered_or_Spayed', models.BooleanField()),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('petId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petImage', models.ImageField(upload_to='static/pet_pics')),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewDate', models.DateField(blank=True, null=True)),
                ('interviewTime', models.TimeField(blank=True, default=None, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.application')),
                ('interviewedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validIdPicture', models.ImageField(upload_to='static/application_pics')),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.application')),
            ],
        ),
        migrations.CreateModel(
            name='HousePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housePicture', models.ImageField(upload_to='static/application_pics')),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.application')),
            ],
        ),
        migrations.CreateModel(
            name='CondoAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condoAgreement', models.ImageField(blank=True, null=True, upload_to='static/application_pics')),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
