# Generated by Django 4.2.7 on 2023-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='modeOfInterview',
            field=models.CharField(choices=[('Online Interview', 'Online Interview'), ('On-site Interview', 'Onsite-Interview'), ('Accepted', 'Accepted'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='preferredModeOfInterview',
            field=models.CharField(choices=[('Online Interview', 'Online Interview'), ('On-site Interview', 'Onsite-Interview'), ('Accepted', 'Accepted'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Interviewing', 'Interviewing'), ('Accepted', 'Accepted'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
