# Generated by Django 4.2.2 on 2023-11-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='adoptedBy',
        ),
    ]
