# Generated by Django 4.2.7 on 2023-11-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_application_inpersonvisittime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='inPersonVisitTime',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='interviewTime',
            field=models.TimeField(default=None, null=True),
        ),
    ]
