# Generated by Django 4.2.7 on 2023-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_application_inpersonvisittime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='modeOfInterview',
            field=models.CharField(choices=[('Online', 'Online'), ('On-site', 'On-site')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='preferredModeOfInterview',
            field=models.CharField(choices=[('Online', 'Online'), ('On-site', 'On-site')], default='', max_length=50),
        ),
    ]
