# Generated by Django 4.2.2 on 2023-11-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='caption',
            field=models.CharField(default='', max_length=100),
        ),
    ]
